In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Reshape

# Function to generate training data for matrix transpose
def generate_data(num_samples, matrix_size):
    X = np.random.rand(num_samples, matrix_size, matrix_size)
    Y = np.transpose(X, axes=(0, 2, 1))  # Transpose each matrix
    return X, Y

# Parameters
num_samples = 1000  # Number of samples to generate
matrix_size = 3     # Size of the matrix (e.g., 3x3)

# Generate data
X_train, Y_train = generate_data(num_samples, matrix_size)

# Neural network model
model = Sequential([
    Flatten(input_shape=(matrix_size, matrix_size)),  # Flatten the input matrix
    Dense(64, activation='relu'),  # Hidden layer with 64 neurons
    Dense(matrix_size * matrix_size),  # Output layer
    Reshape((matrix_size, matrix_size))  # Reshape output to the original matrix shape
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X_train, Y_train, epochs=100, batch_size=32, verbose=1)

# Test the model
X_test, Y_test = generate_data(10, matrix_size)  # Generate some test data
predictions = model.predict(X_test)

# Display results
for i in range(5):
    print(f"Original Matrix:\n{X_test[i]}")
    print(f"True Transpose:\n{Y_test[i]}")
    print(f"Predicted Transpose:\n{predictions[i]}")
    print("-" * 30)


Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3078
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0897
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0542
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0340 
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0185
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0101
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0052
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0028 
Epoch 9/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0016
Epoch 10/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0011 
Epoch 11/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.1205e-04 
Epoch 12/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.3445e-04  
Epoch 13/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6858e-04  
Epoch 14/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5.9704e-04 
Epoch 15/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Reshape

# Function to generate training data for matrix transpose
def generate_data(num_samples, matrix_size):
    X = np.random.rand(num_samples, matrix_size, matrix_size)
    Y = np.transpose(X, axes=(0, 2, 1))  # Transpose each matrix
    return X, Y

# Parameters
num_samples = 1000  # Number of samples to generate
matrix_size = 3     # Size of the matrix (e.g., 3x3)

# Generate data
X_train, Y_train = generate_data(num_samples, matrix_size)

# Neural network model
model = Sequential([
    Flatten(input_shape=(matrix_size, matrix_size)),  # Flatten the input matrix
    Dense(64, activation='relu'),  # Hidden layer with 64 neurons
    Dense(matrix_size * matrix_size),  # Output layer
    Reshape((matrix_size, matrix_size))  # Reshape output to the original matrix shape
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X_train, Y_train, epochs=10, batch_size=32, verbose=1)

# Test the model
X_test, Y_test = generate_data(10, matrix_size)  # Generate some test data
predictions = model.predict(X_test)

# Display results
for i in range(5):
    print(f"Original Matrix:\n{X_test[i]}")
    print(f"True Transpose:\n{Y_test[i]}")
    print(f"Predicted Transpose:\n{predictions[i]}")
    print("-" * 30)


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3171   
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 0.1074
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - loss: 0.0730
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 0.0483
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - loss: 0.0304
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - loss: 0.0200
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - loss: 0.0114
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - loss: 0.0068
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - loss: 0.0038
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0024 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Original Matrix:
[[0.92624183 0.41456599 0.23414402]
 [0.14412409 0.97176004 0.26384753]
 [0.11679153 0.89431167 0.14210249]]
True Transpose:
[[0.92624183 0.14412409 0.11679153]
 [0.41456599 0.97176004 0.89431167]
 [0.23414402 0.26384753 0.14210249]]
Predicted Transpose:
[[0.8483658  0.2270