In [ ]:
import numpy as np
#using numpy addition
X = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

Y = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

result = np.array(X) + np.array(Y)

print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
#using neural netork
def matrix_addition_neural_network(matrix1, matrix2):
    #checking if they have same order like nxn
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same shape for addition.")

    # in neural network addition is done using adding weights and bias
    weights = np.ones(matrix1.shape)
    bias = np.zeros(matrix1.shape)
    output = (matrix1 * weights) + (matrix2 * weights) + bias

    return output

matrix1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
matrix2 = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])
result = matrix_addition_neural_network(matrix1, matrix2)


print( result)


[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
